const MAX_CARGO_PRICE_MODIFIER = 4.0 //which means min value is 1/4
const MIN_CARGO_AMOUNT_IN_MARKET = 0
const MAX_CARGO_AMOUNT_IN_MARKET = 100
const MIN_NUM_SHIPS_IN_SHIPYARD = 0
const MAX_NUM_SHIPS_IN_SHIPYARD = 3
const MAX_ENCOUNTER_WEIGHT = 4

const MAP_VIEW_RANGE = 20 // in coordinate units
const MIN_MAP_VIEW_RANGE = 10
const MAX_MAP_VIEW_RANGE = 40
const GRID_WIDTH = 80;  // Characters wide
const GRID_HEIGHT = 40; // Characters tall
const FONT_FAMILY = 'Courier New, monospace';
const MIN_FONT_SIZE = 16;   // Minimum font size in pixels
const MAX_FONT_SIZE = 48;  // Maximum font size in pixels
const GALAXY_MAP_WIDTH = 50 // Characters
const GALAXY_MAP_HEIGHT = 30 // Characters
const COMBAT_MAP_WIDTH = 50 // Characters
const COMBAT_MAP_HEIGHT = 30 // Characters

const MIN_NUM_SYSTEMS = 200
const MAX_NUM_SYSTEMS = 300
const MIN_SYSTEM_X = -100
const MAX_SYSTEM_X = 100
const MIN_SYSTEM_Y = -100
const MAX_SYSTEM_Y = 100
const MAX_SYSTEM_POPULATION = 10000 // in millions
const SAVE_FILE_PREFIX = 'void_trader_save_'
const MAX_SAVES = 5
const SHIP_MIN_STAT_VARIATION = 0.5
const SHIP_MAX_STAT_VARIATION = 2

const AVERAGE_SHIP_HULL = 20
const AVERAGE_SHIP_SHIELDS = 10
const AVERAGE_SHIP_CARGO = 20
const AVERAGE_SHIP_FUEL = 10
const AVERAGE_SHIP_ENGINE_LEVEL = 10
const AVERAGE_SHIP_LASER_LEVEL = 10
const AVERAGE_SHIP_RADAR_LEVEL = 10
const AVERAGE_JOURNEY_DAYS_PER_LY = 1
const AVERAGE_JOURNEY_ENCOUNTER_CHANCE_PER_DAY = 0.5

const ENCOUNTER_MIN_SHIP_DISTANCE = 25
const ENCOUNTER_MAX_SHIP_DISTANCE = 50
const ENCOUNTER_MAX_RADIUS = 100
const ENCOUNTER_MAP_VIEW_RANGE = 80 // in coordinate units
const ENCOUNTER_MIN_MAP_VIEW_RANGE = 20
const ENCOUNTER_MAX_MAP_VIEW_RANGE = 120

const STAR_SYSTEM_MIN_DISTANCE_FROM_NEIGHBORS = 5
const STAR_SYSTEM_MAX_DISTANCE_FROM_NEIGHBORS = 20
const MIN_COMBAT_ASTEROIDS = 5
const MAX_COMBAT_ASTEROIDS = 25
const ASTEROID_SIZE = 1
const SHIP_SIZE = 1
const CHANCE_TO_LASER_OBSTRUCTION = 0.5
const ENEMY_FLEE_AT_HULL_RATIO = 0.25
const ENEMY_MIN_LASER_HIT_CHANCE = 0.5
const ENEMY_MIN_CARGO_RATIO = 0
const ENEMY_MAX_CARGO_RATIO = 1
const ENEMY_HAS_CARGO_TYPE_CHANCE = 0.5
const ENEMY_SHIP_HULL_DAMAGED_CHANCE = 0.5
const ENEMY_DAMAGED_SHIP_MIN_HULL_RATIO = 0.25
const ENEMY_DAMAGED_SHIP_MAX_HULL_RATIO = 1

const REPUTATION_EFFECT_ON_ATTACK_CIVILIAN = -5
const REPUTATION_EFFECT_ON_ATTACK_AUTHORITIES = -10
const REPUTATION_EFFECT_ON_ATTACK_CRIMINALS = 5
const BOUNTY_INCREASE_ON_ATTACK_CIVILIANS = 1000
const BOUNTY_INCREASE_ON_ATTACK_AUTHORITIES = 2000

const DAYS_IN_JAIL_PER_1000CR_BOUNTY = 7
const EXPERIENCE_FROM_AVERAGE_VICTORY = 100
const EXPERIENCE_FROM_TRADING_1000_CR = 10
const EXPERIENCE_FROM_AVERAGE_ESCAPE = 10

const FUEL_COST_PER_UNIT = 1
const HULL_REPAIR_COST_PER_UNIT = 10