const MIN_CARGO_PRICE_MODIFIER = 0.25
const MAX_CARGO_PRICE_MODIFIER = 4.0
const MIN_CARGO_AMOUNT_IN_MARKET = 0
const MAX_CARGO_AMOUNT_IN_MARKET = 100
const MIN_NUM_SHIPS_IN_SHIPYARD = 0
const MAX_NUM_SHIPS_IN_SHIPYARD = 3
const MIN_ENCOUNTER_WEIGHT = 0.1
const MAX_ENCOUNTER_WEIGHT = 4

const MAP_VIEW_RANGE = 20 // in coordinate units
const MIN_MAP_VIEW_RANGE = 10
const MAX_MAP_VIEW_RANGE = 40
const GALAXY_MAP_WIDTH_PERCENT = 0.5 // 50% of screen width
const GALAXY_MAP_HEIGHT_PERCENT = 0.5 // 50% of screen height
const GALAXY_MAP_WIDTH_BONUS = 5 // Extra columns
const GALAXY_MAP_HEIGHT_BONUS = 5 // Extra rows

const MIN_NUM_SYSTEMS = 200
const MAX_NUM_SYSTEMS = 300
const MIN_SYSTEM_X = -100
const MAX_SYSTEM_X = 100
const MIN_SYSTEM_Y = -100
const MAX_SYSTEM_Y = 100
const MAX_SYSTEM_POPULATION = 10000 // in millions
const SAVE_FILE_PREFIX = 'void_trader_save_'
const MAX_SAVES = 5
const SHIP_MIN_STAT_VARIATION = 0.5
const SHIP_MAX_STAT_VARIATION = 2

const AVERAGE_SHIP_HULL = 40
const AVERAGE_SHIP_SHIELDS = 40
const AVERAGE_SHIP_CARGO = 20
const AVERAGE_SHIP_FUEL = 10
const AVERAGE_SHIP_ENGINE_LEVEL = 10
const AVERAGE_SHIP_LASER_LEVEL = 10
const AVERAGE_SHIP_RADAR_LEVEL = 10
const AVERAGE_JOURNEY_DAYS_PER_LY = 1
const AVERAGE_JOURNEY_ENCOUNTER_CHANCE_PER_DAY = 0.5

const ENCOUNTER_MIN_SHIP_DISTANCE = 25
const ENCOUNTER_MAX_SHIP_DISTANCE = 50
const ENCOUNTER_MAX_RADIUS = 100
const ENCOUNTER_MAP_VIEW_RANGE = 80 // in coordinate units
const ENCOUNTER_MIN_MAP_VIEW_RANGE = 20
const ENCOUNTER_MAX_MAP_VIEW_RANGE = 120
const ENCOUNTER_MAP_WIDTH_PERCENT = 0.5 // 50% of screen width
const ENCOUNTER_MAP_HEIGHT_PERCENT = 0.5 // 50% of screen height
const ENCOUNTER_MAP_WIDTH_BONUS = 5 // Extra columns
const ENCOUNTER_MAP_HEIGHT_BONUS = 5 // Extra rows

const STAR_SYSTEM_MIN_DISTANCE_FROM_NEIGHBORS = 5
const STAR_SYSTEM_MAX_DISTANCE_FROM_NEIGHBORS = 20

