/**
 * Space Travel Map Config
 */

const SpaceTravelConfig = {
    VIEW_FOV: 75,
    NEAR_PLANE: 0.0001,
    PANEL_HEIGHT: 7,

    LY_TO_AU: 63241,

    EARTH_SIZE_AU: 1,
    SHIP_SIZE_AU: 1 / 10000,
    STATION_SIZE_AU: 1 / 100,

    SHIP_SPEED_PER_ENGINE: 10,
    SHIP_ACCEL_PER_ENGINE: 0.8,
    TURN_DEG_PER_SEC: 90,

    STAR_RENDER_DISTANCE_AU: 2_000_000,
    STARFIELD_RADIUS_AU: 8_000_000,
    STARFIELD_COUNT: 1200,

    DUST_PARTICLE_COUNT: 40,
    DUST_PARTICLE_RANGE_SHIP_LENGTHS: 100,
    DUST_PARTICLE_SPAWN_RADIUS_SHIP_LENGTHS: 60,
    DUST_PARTICLE_SYMBOL: '·',
    DUST_PARTICLE_LINE_SYMBOLS: true,
    DUST_PARTICLE_LINE_SPEED_THRESHOLD: 0.0002,
    DUST_PARTICLE_VELOCITY_BIAS: 0.25,
    DUST_PARTICLE_MIN_DISTANCE_SHIP_LENGTHS: 5,
    DUST_PARTICLE_MAX_DISTANCE_SHIP_LENGTHS: 80,
    DUST_PARTICLE_EDGE_BAND_SHIP_LENGTHS: 15,
    DUST_SCREEN_SPEED_EPSILON: 0.00005,

    STATION_POSSIBLE_RANGE_AU: 5_000_000,
    STATION_VISIBLE_RANGE_AU: 1_500_000,

    DEBUG_STATION_LOG: false,
    DEBUG_STATION_VISIBILITY: false,
    DEBUG_STATION_COLLISION: true,
    STATION_FACE_DEPTH_BIAS: 0.0005,
    STATION_EDGE_DEPTH_BIAS: 0.0005,
    STATION_ENTRANCE_DIR: { x: 0, y: 0, z: 1 },
    STATION_ENTRANCE_DOT: 0.85,
    STATION_BOUNCE_DAMPING: 0.6,
    STATION_COLLISION_COOLDOWN_MS: 600,
    STATION_COLLISION_RADIUS_MULT: 0.8,
    STATION_COLLISION_MIN_SPEED: 0.2 / 60,
    STATION_COLLISION_MAX_ENTRANCE_DOT: 0.7,
    STATION_COLLISION_SPEED_PER_HULL: 5,
    DAMAGE_FLASH_DURATION_MS: 500,
    DAMAGE_FLASH_ALPHA: 0.5,
    SYSTEM_BODY_SHADE_MAX_DISTANCE_AU: 50,
    SYSTEM_BODY_LABEL_DISTANCE_AU: 8,

    BASE_ACCEL_MULT: 2,
    BOOST_ACCEL_MULT: 50,
    BOOST_MAX_SPEED_MULT: 100,
    BOOST_FUEL_PER_SEC: 0.1,
    BOOST_TINT_MAX: 0.25,
    BOOST_TINT_RAMP_POWER: 2,
    BOOST_COOLDOWN_SEC: 5,
    BOOST_TINT_MIN: 0.1,
    BOOST_STREAK_DELAY_MS: 2000,
    BOOST_BRAKE_MULT: 8,
    BOOST_STREAK_GROWTH_MS: 2000,
    BOOST_READY_SPEED_RATIO: 0.99,
    BOOST_COOLDOWN_DECEL_SEC: 2,
    BOOST_COOLDOWN_END_SPEED_MULT: 0.5,

    LASER_FIRE_DURATION_MS: 500,
    LASER_REGEN_SEC: 0.5,
    SHIELD_REGEN_SEC: 0.5,
    LASER_COLOR: '#ff4d4d',
    LASER_DEPTH: 0.00005,

    STAR_HEAT_DAMAGE_PER_SEC: 10,
    STAR_HEAT_RANGE_MULT: 4,

    ASCII_LOG_INTERVAL_MS: 2000,

    POSSIBLE_STATION_CHECK_FRAMES: 300,
    VISIBLE_STATION_CHECK_FRAMES: 30
};
