/**
 * Space Travel Map Config
 */

const SpaceTravelConfig = {
    VIEW_FOV: 75,
    NEAR_PLANE: 0.0001,
    PANEL_HEIGHT: 9,
    PANEL_CURSOR_SCROLL_ROWS: 3,

    PORTAL_DISTANCE_AU: 0.01,
    PORTAL_RADIUS_AU: 0.0025,
    PORTAL_DURATION_MS: 5000,
    PORTAL_EXPAND_DURATION_MS: 2000,
    PORTAL_SEGMENTS: 32,
    PORTAL_TINT_STRENGTH: 0.6,
    PORTAL_EMPTY_BRIGHTNESS: 0.25,
    PORTAL_MIN_SPAWN_DISTANCE_AU: 0.02,
    WARP_ANIM_DURATION_MS: 4000,
    WARP_TINT_RAMP_MS: 6000,
    WARP_FADE_OUT_MS: 1000,

    LY_TO_AU: 63241,

    SHIP_SPEED_PER_ENGINE: 1 / 600, // In AU per second per engine level. This means a ship with 10 engine level would move at 1/60 AU/s, or about 1 AU per minute.
    SHIP_ACCEL_PER_ENGINE: 1 / 60, // In AU/s² per engine level. This means a ship with 10 engine level would have an acceleration of 0.00005 AU/s², allowing it to reach its top speed in about 20 seconds.
    TURN_DEG_PER_SEC: 90,
    ROLL_DEG_PER_SEC: 90,

    TIME_SCALE_GAME_SECONDS_PER_REAL_SECOND: 60,
    GAME_SECONDS_PER_DAY: 86400,

    SYSTEM_BODY_SCREEN_SCALE: 10,
    SYSTEM_BODY_PHYSICS_SCALE: 10,
    CHAR_CELL_ASPECT_RATIO: null,
    SHIP_ROCKET_TRAIL_OFFSET_SCALE: 10000, // Scales visual-model-based rear offset used for rocket trail spawn point
    SHIP_SYMBOL_ONLY: true,
    SHIP_USE_ANGLE_SPRITES: true,
    SHIP_SPRITE_MAX_DISTANCE_AU: 1,
    SHIP_SPRITES,
    SHIP_SHOW_DISTANCE_LABELS: true,
    SHIP_SPAWN_DISTANCE_AU: 0.2,  // Reduced 10x (was 2.0)
    SHIP_SPAWN_SPREAD_AU: 0.03,   // Reduced 10x (was 0.3)
    SHIP_COLLISION_RADIUS_MULT: 1.2,
    SHIP_COLLISION_DISTANCE_MULT: 0.5,
    SHIP_MIN_COLLISION_DISTANCE_AU: 0.01,
    SHIP_BOUNCE_DAMPING: 0.7,
    SHIP_COLLISION_COOLDOWN_MS: 400,
    DISABLED_SHIP_LOOT_ARM_MS: 1000,
    DISABLED_SHIP_LOOT_MAX_SPEED_AU_PER_SEC: 0.01,
    DISABLED_SHIP_LOOT_DISTANCE_MULT: 0.5,
    PATROL_WAIT_MIN_SEC: 5,
    PATROL_WAIT_MAX_SEC: 15,
    
    // Laser damage to ships
    LASER_DAMAGE_MIN_RATIO: 0.5,  // Minimum 50% of laser energy as damage
    LASER_DAMAGE_MAX_RATIO: 1.0,  // Maximum 100% of laser energy as damage
    
    // Ship damage flash settings
    SHIP_FLASH_DURATION_MS: 1000,  // 1 second total flash window
    SHIP_FLASH_COUNT: 4,
    SHIP_FLASH_SHIELD_COLOR: '#ffffff',  // White for shield damage
    SHIP_FLASH_HULL_COLOR: '#ff0000',    // Red for hull damage
    SHIP_FLASH_ABANDONED_COLOR: '#8b0000', // Dark red for abandoned ships
    
    // Ram damage
    RAM_DAMAGE_RATIO: 0.3,  // 30% of collision speed as damage
    RAM_DAMAGE_MIN: 5,      // Minimum ram damage
    STATION_SCREEN_SCALE: 100,
    STATION_MIN_NON_SYMBOL_SIZE_CHARS: 3,
    STATION_MIN_NON_SYMBOL_MAX_SCALE_MULT: 4,
    STATION_PHYSICS_SCALE: 100,
    STATION_SPAWN_DISTANCE_MULT: 25,
    STATION_SPAWN_MIN_DISTANCE_AU: 0.001,

    STAR_RENDER_DISTANCE_AU: 2_000_000,
    STARFIELD_RADIUS_AU: 8_000_000,
    STARFIELD_COUNT: 1200,

    DUST_PARTICLE_COUNT: 40,
    DUST_PARTICLE_RANGE_SHIP_LENGTHS: 2.5,
    DUST_PARTICLE_SPAWN_RADIUS_SHIP_LENGTHS: 1.5,
    DUST_PARTICLE_SYMBOL: '·',
    DUST_PARTICLE_LINE_SYMBOLS: true,
    DUST_PARTICLE_LINE_SPEED_THRESHOLD: 0.5,
    DUST_PARTICLE_VELOCITY_BIAS: 0.25,
    DUST_PARTICLE_MIN_DISTANCE_SHIP_LENGTHS: 0.125,
    DUST_PARTICLE_MAX_DISTANCE_SHIP_LENGTHS: 2,
    DUST_PARTICLE_EDGE_BAND_SHIP_LENGTHS: 0.375,
    DUST_SCREEN_SPEED_EPSILON: 0.00005,

    // Rocket trail clouds
    ROCKET_TRAIL_ENABLED: true,
    ROCKET_TRAIL_SPAWN_INTERVAL_MS: 400,
    ROCKET_TRAIL_FADE_MS: 8000,
    ROCKET_TRAIL_VISIBLE_DISTANCE_AU: 2.5,
    ROCKET_TRAIL_CHAR: '*',
    ROCKET_TRAIL_COLOR: '#ff8a00',
    ROCKET_TRAIL_MIN_SPEED_AU_PER_SEC: 0.000001,
    DEBUG_ROCKET_TRAIL_LOG: true,
    DEBUG_ROCKET_TRAIL_LOG_EVERY_MS: 1000,

    // In-space NPC encounter fleets
    NPC_ENCOUNTER_WEIGHT_DIVISOR: 60,
    NPC_ENCOUNTER_MIN_DISTANCE_FOR_RATE_AU: 0.1,
    NPC_FLEET_MIN_SHIPS: 1,
    NPC_FLEET_MAX_SHIPS: 3,
    NPC_FLEET_SPAWN_RADIUS_AU: 1.2,
    NPC_FLEET_SPAWN_SPREAD_AU: 0.6,
    NPC_FLEET_SPAWN_Z_SPREAD_AU: 0.4,
    NPC_FLEET_DESTINATION_REACHED_AU: 0.5,
    NPC_FLEET_DESPAWN_DISTANCE_AU: 10,
    NPC_PURSUIT_SPEED_MULT: 1,
    NPC_CRUISE_SPEED_MULT: 0.8,
    NPC_HOSTILE_SPEED_MULT: 1.1,
    NPC_HAIL_RANGE_AU: 1,
    NPC_HAIL_POPOVER_MS: 900,
    NPC_HAIL_RESPONSE_TIMEOUT_MS: 5000,
    NPC_FLEET_FIRE_INTERVAL_MS: 1200,
    NPC_FLEET_WEAPON_RANGE_AU: 2,
    NPC_COMBAT_FIRE_FOV_DEG: 60,
    NPC_COMBAT_AIM_JITTER_AU: 0.015,
    NPC_COMBAT_LASER_VISIBLE_MS: 180,
    NPC_SHOT_MIN_DAMAGE: 2,
    NPC_SHOT_MAX_DAMAGE: 6,

    STATION_POSSIBLE_RANGE_AU: 5_000_000,
    STATION_VISIBLE_RANGE_AU: 1_500_000,

    PLANET_DOCK_RADIUS_MULT: 1.05,

    DEBUG_STATION_LOG: false,
    DEBUG_STATION_VISIBILITY: false,
    DEBUG_STATION_COLLISION: false,
    DEBUG_STATION_RASTER: false,
    DEBUG_STATION_FACE_INDEX: null,
    DEBUG_STATION_FACE_OUTLINE: false,
    DEBUG_STATION_FACE_FILL_MODE: 'tri',
    DEBUG_ROLL_LOG: true,
    DEBUG_CLOSE_SHIP_LOG: true,
    DEBUG_CLOSE_SHIP_DISTANCE_AU: 0.01,
    RENDER_SYSTEM_BODIES: true,
    STATION_FACE_DEPTH_BIAS: 0.0005,
    STATION_EDGE_DEPTH_BIAS: 0.0005,
    STATION_ENTRANCE_DIR: { x: 1, y: 0, z: 0 },  // Desired world-space direction for entrance (model's +Z will be rotated to this)
    STATION_ENTRANCE_YAW_DEG: 0,
    STATION_ENTRANCE_DOT: 0.85,
    STATION_BOUNCE_DAMPING: 0.6,
    STATION_SLIDE_DAMPING: 0.9,
    STATION_COLLISION_COOLDOWN_MS: 600,
    STATION_COLLISION_RADIUS_MULT: 1,
    STATION_DOCK_RADIUS_MULT: 0.6,
    STATION_COLLISION_MIN_SPEED: 0.005 / 60,
    STATION_COLLISION_MAX_ENTRANCE_DOT: 0.7,
    STATION_COLLISION_DAMAGE_NORMAL_RATIO: 0.35,
    STATION_COLLISION_SPEED_PER_HULL: 0.5,
    DAMAGE_FLASH_DURATION_MS: 500,
    DAMAGE_FLASH_ALPHA: 0.5,
    DEATH_FADE_TO_RED_SEC: 1,
    DEATH_FADE_TO_BLACK_SEC: 1,
    DOCK_FADE_TO_BLACK_SEC: 1,
    SYSTEM_BODY_SHADE_MAX_DISTANCE_AU: 50,
    SYSTEM_BODY_LABEL_DISTANCE_AU: 8,

    BASE_ACCEL_MULT: 2,
    BOOST_ACCEL_MULT: 50,
    BOOST_MAX_SPEED_MULT: 100,
    BOOST_FUEL_PER_SEC: 0.1,
    BOOST_TINT_MAX: 0.25,
    BOOST_TINT_RAMP_SEC: 1.0,  // 2x slower ramp (was 0.5)
    BOOST_TINT_FADE_SEC: 1.0,  // Visual cooldown time
    BOOST_COOLDOWN_SEC: 5,
    BOOST_TINT_MIN: 0,
    BOOST_STREAK_DELAY_MS: 1000,  // Reduced from 2000 to start star streaks 2x sooner during boost
    BOOST_STREAK_PERSIST_MS: 1000,
    BOOST_BRAKE_MULT: 8,
    BOOST_STREAK_GROWTH_MS: 2000,
    BOOST_READY_SPEED_RATIO: 0.99,
    BOOST_COOLDOWN_DECEL_SEC: 1,
    BOOST_COOLDOWN_END_SPEED_MULT: 0.5,
    AUTO_NAV_BOOST_STOP_SPEED_MULT: 10,

    LASER_FIRE_DURATION_MS: (typeof SPACE_TRAVEL_LASER_TRAVEL_DURATION_MS !== 'undefined')
        ? SPACE_TRAVEL_LASER_TRAVEL_DURATION_MS
        : 125,
    LASER_IMPACT_RADIUS_AU: (typeof SHIP_SIZE_AU !== 'undefined') ? (SHIP_SIZE_AU * 1.5) : 0.000001,
    LASER_REGEN_SEC: 1,
    SHIELD_REGEN_SEC: 5,
    LASER_COLOR: '#ff4d4d',
    LASER_DEPTH: 0.00005,

    STAR_HEAT_DAMAGE_PER_SEC: 10,
    STAR_HEAT_RANGE_MULT: 10,
    STAR_HEAT_MAX_DISTANCE_AU: null,

    ASCII_LOG_INTERVAL_MS: 2000,

    // Station visibility checks run every frame
};
