/**
 * Space Travel Map Config
 */

const SpaceTravelConfig = {
    VIEW_FOV: 75,
    NEAR_PLANE: 0.0001,
    PANEL_HEIGHT: 9,
    PANEL_CURSOR_SCROLL_ROWS: 3,

    PORTAL_DISTANCE_AU: 0.01,
    PORTAL_RADIUS_AU: 0.0025,
    PORTAL_DURATION_MS: 5000,
    PORTAL_EXPAND_DURATION_MS: 2000,
    PORTAL_SEGMENTS: 32,
    PORTAL_TINT_STRENGTH: 0.6,
    PORTAL_EMPTY_BRIGHTNESS: 0.25,
    PORTAL_MIN_SPAWN_DISTANCE_AU: 0.02,
    WARP_ANIM_DURATION_MS: 8000,
    WARP_TINT_RAMP_MS: 6000,
    WARP_FADE_OUT_MS: 1000,

    LY_TO_AU: 63241,

    SHIP_SPEED_PER_ENGINE: 1 / 600, // In AU per second per engine level. This means a ship with 10 engine level would move at 1/60 AU/s, or about 1 AU per minute.
    SHIP_ACCEL_PER_ENGINE: 1 / 60, // In AU/s² per engine level. This means a ship with 10 engine level would have an acceleration of 0.00005 AU/s², allowing it to reach its top speed in about 20 seconds.
    TURN_DEG_PER_SEC: 90,
    ROLL_DEG_PER_SEC: 90,

    TIME_SCALE_GAME_SECONDS_PER_REAL_SECOND: 60,
    GAME_SECONDS_PER_DAY: 86400,

    SYSTEM_BODY_SCREEN_SCALE: 10,
    SYSTEM_BODY_PHYSICS_SCALE: 10,
    CHAR_CELL_ASPECT_RATIO: null,
    STATION_SCREEN_SCALE: 100,
    STATION_PHYSICS_SCALE: 100,
    STATION_SPAWN_DISTANCE_MULT: 25,
    STATION_SPAWN_MIN_DISTANCE_AU: 0.001,

    STAR_RENDER_DISTANCE_AU: 2_000_000,
    STARFIELD_RADIUS_AU: 8_000_000,
    STARFIELD_COUNT: 1200,

    DUST_PARTICLE_COUNT: 40,
    DUST_PARTICLE_RANGE_SHIP_LENGTHS: 2.5,
    DUST_PARTICLE_SPAWN_RADIUS_SHIP_LENGTHS: 1.5,
    DUST_PARTICLE_SYMBOL: '·',
    DUST_PARTICLE_LINE_SYMBOLS: true,
    DUST_PARTICLE_LINE_SPEED_THRESHOLD: 0.5,
    DUST_PARTICLE_VELOCITY_BIAS: 0.25,
    DUST_PARTICLE_MIN_DISTANCE_SHIP_LENGTHS: 0.125,
    DUST_PARTICLE_MAX_DISTANCE_SHIP_LENGTHS: 2,
    DUST_PARTICLE_EDGE_BAND_SHIP_LENGTHS: 0.375,
    DUST_SCREEN_SPEED_EPSILON: 0.00005,

    STATION_POSSIBLE_RANGE_AU: 5_000_000,
    STATION_VISIBLE_RANGE_AU: 1_500_000,

    PLANET_DOCK_RADIUS_MULT: 1.05,

    DEBUG_STATION_LOG: false,
    DEBUG_STATION_VISIBILITY: false,
    DEBUG_STATION_COLLISION: false,
    DEBUG_STATION_RASTER: false,
    DEBUG_STATION_FACE_INDEX: null,
    DEBUG_STATION_FACE_OUTLINE: false,
    DEBUG_STATION_FACE_FILL_MODE: 'tri',
    DEBUG_ROLL_LOG: true,
    RENDER_SYSTEM_BODIES: true,
    STATION_FACE_DEPTH_BIAS: 0.0005,
    STATION_EDGE_DEPTH_BIAS: 0.0005,
    STATION_ENTRANCE_DIR: { x: 1, y: 0, z: 0 },  // Desired world-space direction for entrance (model's +Z will be rotated to this)
    STATION_ENTRANCE_YAW_DEG: 0,
    STATION_ENTRANCE_DOT: 0.85,
    STATION_BOUNCE_DAMPING: 0.6,
    STATION_SLIDE_DAMPING: 0.9,
    STATION_COLLISION_COOLDOWN_MS: 600,
    STATION_COLLISION_RADIUS_MULT: 1,
    STATION_DOCK_RADIUS_MULT: 0.6,
    STATION_COLLISION_MIN_SPEED: 0.005 / 60,
    STATION_COLLISION_MAX_ENTRANCE_DOT: 0.7,
    STATION_COLLISION_DAMAGE_NORMAL_RATIO: 0.35,
    STATION_COLLISION_SPEED_PER_HULL: 0.5,
    DAMAGE_FLASH_DURATION_MS: 500,
    DAMAGE_FLASH_ALPHA: 0.5,
    DEATH_FADE_TO_RED_SEC: 1,
    DEATH_FADE_TO_BLACK_SEC: 1,
    DOCK_FADE_TO_BLACK_SEC: 1,
    SYSTEM_BODY_SHADE_MAX_DISTANCE_AU: 50,
    SYSTEM_BODY_LABEL_DISTANCE_AU: 8,

    BASE_ACCEL_MULT: 2,
    BOOST_ACCEL_MULT: 50,
    BOOST_MAX_SPEED_MULT: 100,
    BOOST_FUEL_PER_SEC: 0.1,
    BOOST_TINT_MAX: 0.0625,
    BOOST_TINT_RAMP_SEC: 4,
    BOOST_TINT_FADE_SEC: 2.5,
    BOOST_COOLDOWN_SEC: 5,
    BOOST_TINT_MIN: 0,
    BOOST_STREAK_DELAY_MS: 1000,  // Reduced from 2000 to start star streaks 2x sooner during boost
    BOOST_BRAKE_MULT: 8,
    BOOST_STREAK_GROWTH_MS: 2000,
    BOOST_READY_SPEED_RATIO: 0.99,
    BOOST_COOLDOWN_DECEL_SEC: 1,
    BOOST_COOLDOWN_END_SPEED_MULT: 0.5,
    AUTO_NAV_BOOST_STOP_SPEED_MULT: 10,

    LASER_FIRE_DURATION_MS: 250,
    LASER_REGEN_SEC: 1,
    SHIELD_REGEN_SEC: 5,
    LASER_COLOR: '#ff4d4d',
    LASER_DEPTH: 0.00005,

    STAR_HEAT_DAMAGE_PER_SEC: 10,
    STAR_HEAT_RANGE_MULT: 10,
    STAR_HEAT_MAX_DISTANCE_AU: null,
    STAR_LUMINOSITY_BY_TYPE: {
        STAR_RED_DWARF: 0.02,
        STAR_YELLOW_DWARF: 1,
        STAR_WHITE_DWARF: 0.1,
        STAR_RED_GIANT: 1000,
        STAR_BLUE_GIANT: 10000,
        STAR_NEUTRON: 0.05,
        STAR_BLACK_HOLE: 0
    },

    ASCII_LOG_INTERVAL_MS: 2000,

    // Station visibility checks run every frame
};
